#!/system/bin/sh

# Add to one of the init scripts, e.g. init.target.rc:
# service analyze_svc /system/bin/logwrapper /system/bin/analyze_service
#	class main
#	socket analyze_svc1 stream 0660 root system
#	socket analyze_svc2 stream 0660 root inet

# Dump the environment

set

# List sockets under /dev/socket

ls -al /dev/socket

